version: '3.8'

services:
  movie-data-capture:
    build: .
    container_name: mdc-go
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 配置文件
      - ./config.yaml:/app/config.yaml:ro
      # 输入目录（电影文件）
      - ./movies:/app/movies:ro
      # 输出目录
      - ./JAV_output:/app/JAV_output
      # 失败文件目录
      - ./failed:/app/failed
      # 日志目录
      - ./logs:/app/logs
    command: ["-path", "/app/movies", "-logdir", "/app/logs"]
    
    # 网络配置（如果需要代理）
    # network_mode: "host"
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'